export enum StorageKeys {
    NAVIGATION_PERSISTENCE = 'NAVIGATION_STATE',
    ROOT_STATE_STORAGE = 'root-v1',
    FIRST_LAUNCH = 'FIRST_LAUNCH',
    APP_LANGUAGE = 'APP_LANGUAGE',
    APP_THEME = 'APP_THEME',
}